export const QUESTIONS_POOL = [
    "Who is most likely to become a millionaire first?",
    "Who would survive the longest in a zombie apocalypse?",
    "Who is most likely to win a reality TV show?",
    "Who would make the best stand-up comedian?",
    "Who is most likely to go viral on social media?",
    "Who would be the best detective in a mystery case?",
    "Who is most likely to forget their own birthday?",
    "Who would be the best at impersonating celebrities?",
    "Who would be the best secret agent?",
    "Who is most likely to accidentally text the wrong person something embarrassing?",
    "Who is most likely to live in a different country?",
    "Who would be the best at giving life advice?",
    "Who is most likely to become a famous artist?",
    "Who would win a 'most unpredictable' award?",
    "Who is most likely to have the best fashion sense?",
    "Who is most likely to write a best-selling book?",
    "Who would have the most interesting travel stories?",
    "Who is most likely to learn a new language in a month?",
    "Who would have the weirdest hobbies?",
    "Who is most likely to become a motivational speaker?",
    "Who would win an eating contest?",
    "Who is most likely to be a food critic?",
    "Who would survive only on fast food?",
    "Who is most likely to cook the best meal?",
    "Who would try the spiciest dish without hesitation?",
    "Who is most likely to order dessert before the main course?",
    "Who would be the first to finish a buffet challenge?",
    "Who is most likely to invent a new food trend?",
    "Who would survive the longest on just coffee?",
    "Who is most likely to sneak snacks into a movie theater?",
    "Who would be the best CEO of a startup?",
    "Who is most likely to become a professor?",
    "Who would be the best at negotiating deals?",
    "Who is most likely to ace an exam without studying?",
    "Who would accidentally sleep through an important meeting?",
    "Who is most likely to work at their dream job?",
    "Who would forget about an important deadline?",
    "Who is most likely to become a scientist?",
    "Who would get promoted the fastest?",
    "Who is most likely to quit their job and travel the world?",
    "Who would make the best movie director?",
    "Who is most likely to binge-watch an entire TV series in one day?",
    "Who would be the best at trivia games?",
    "Who is most likely to meet a celebrity by accident?",
    "Who would cry the most during a sad movie?",
    "Who is most likely to win a karaoke contest?",
    "Who would be the best DJ at a party?",
    "Who is most likely to cosplay at a convention?",
    "Who would have the best Spotify playlist?",
    "Who is most likely to win a dance battle?"
]